package com.example.demo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "books") // Define the table name in the database
public class Book {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id; // This is the primary key generated by the database

    private String title;
    private String author;
    private int isbn;
    private double price;
    private int quantityInStock;

    // Default constructor
    public Book() {
    }

    public Book(String title, String author, int isbn, double price, int quantityInStock) {
        this.title = title;
        this.author = author;
        this.isbn = isbn;
        this.price = price;
        this.quantityInStock = quantityInStock;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public int getIsbn() {
        return this.isbn;
    }

    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }

    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public int getQuantityInStock() {
        return this.quantityInStock;
    }

    public void setQuantityInStock(int quantityInStock) {
        this.quantityInStock = quantityInStock;
    }
}
